######################################################################
# Automatically generated by qmake (3.0) Mon Jan 20 12:56:16 2014
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = unit-tests
INCLUDEPATH += .
QT += dbus declarative webkitwidgets

# Input
HEADERS += testbrowser.h ../browserviewportitem.h
SOURCES += testbrowser.cpp ../browserviewportitem.cpp
