######################################################################
# Automatically generated by qmake (3.0) Mon Jan 20 12:56:16 2014
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = unit-tests
INCLUDEPATH += .
QT += dbus webkitwidgets

# Input
HEADERS += testbrowser.h ../browserview.h
SOURCES += testbrowser.cpp ../browserview.cpp
