######################################################################
# Automatically generated by qmake (3.0) Mon Jan 20 12:56:16 2014
######################################################################

CONFIG += qtestlib debug qt
TEMPLATE = app
TARGET = browserdbus-tests
INCLUDEPATH += . ../../../common/
QT += dbus webkitwidgets

my_dbus_interfaces.files += ../../../common/IBookmarkManager.xml \
    ../../../common/IUserInput.xml \
    ../../../common/IWebPageWindow.xml \
    ../../../common/IBrowser.xml
my_dbus_interfaces.header_flags = -i ../../../common/browserdefs.h
DBUS_INTERFACES += my_dbus_interfaces

# Input
HEADERS += testbrowserdbus.h ../../../common/browserdbus.h ../../../common/bookmark.h
SOURCES += testbrowserdbus.cpp ../../../common/browserdbus.cpp ../../../common/bookmark.cpp
